services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mmo_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: npm run dev
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mmo_frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
    command: npm run dev
    restart: unless-stopped
